twig:
    form_themes:
        - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
fos_ck_editor:
    default_config: main_config
    base_path: "build/fosckeditor"
    js_path: "build/fosckeditor/ckeditor.js"
    configs:
        main_config:
            toolbar: my_full
            versionCheck: false
            extraAllowedContent: "p{*}(*);select{*}(*);option{*}(*);a{*}(*)"
            htmlEncodeOutput: false
            entities: false
            language: fr
            height: "800px"
            filebrowserImageBrowseRouteParameters:
                provider: "image"
                restrict:
                    uploadTypes:
                        - "image/*"
                    uploadSize: 5
    toolbars:
        configs:
            my_full:
                [
                    "@document",
                    "@clipboard",
                    "@editing",
                    "@tools",
                    "@styles",
                    "@full.forms",
                    "/",
                    "@colors",
                    "@basicstyles",
                    "@paragraph",
                    "@links",
                    "@insert",
                    "/",
                ]
        items:
            document: ["Source", "-"]
            clipboard:
                [
                    "Cut",
                    "Copy",
                    "Paste",
                    "PasteText",
                    "PasteFromWord",
                    "-",
                    "Undo",
                    "Redo",
                ]
            editing: ["Find", "Replace", "-", "SelectAll"]
            basicstyles:
                [
                    "Bold",
                    "Italic",
                    "Underline",
                    "Strike",
                    "Subscript",
                    "Superscript",
                    "-",
                    "CopyFormatting",
                    "RemoveFormat",
                ]
            paragraph:
                [
                    "NumberedList",
                    "BulletedList",
                    "-",
                    "Outdent",
                    "Indent",
                    "-",
                    "-",
                    "JustifyLeft",
                    "JustifyCenter",
                    "JustifyRight",
                    "JustifyBlock",
                    "-",
                ]
            links: ["Link", "Unlink", "Anchor"]
            insert:
                [
                    "Image",
                    "Table",
                    "HorizontalRule",
                    "Smiley",
                    "SpecialChar",
                    "Iframe",
                ]
            styles: ["Styles", "Format", "FontSize"]
            colors: ["TextColor", "BGColor"]
            tools: ["Maximize", "ShowBlocks"]
